#mangowm-simple config by Void Stem

#Wallpaper
exec-once=swaybg -i ~/Pictures/wallpaper.png

#Basic
bind=SUPER,y,reload_config
bind=SUPER,r,spawn,rofi -show drun
bind=SUPER,q,killclient,
bind=SUPER,f,togglefullscreen
bind=SUPER,t,spawn,kitty
bind=SUPER,e,spawn,thunar

#Focus
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down

#Window
bind=SUPER,left,viewtoleft,0
bind=SUPER,right,viewtoright,0
default_mfact=0.5

#Visuals
border_radius=20
borderpx=4
focuscolor=0xf5f5f5ff
